// Generated by tools/generate_architecture.py; do not edit.
import type { RouteObject } from 'react-router';
export const featureRoutes: (RouteObject & { role?: 'learner' | 'counselor' })[] = [
  { path: '/profile', lazy: async () => ({ Component: (await import('../features/profile/public')).ProfilePage }) },
  { path: '/preferences', lazy: async () => ({ Component: (await import('../features/profile/public')).PreferencesPage }) },
  { path: '/learner', role: 'learner', lazy: async () => ({ Component: (await import('../features/learner/public')).LearnerPage }) },
  { path: '/learner/tasks/:id', role: 'learner', lazy: async () => ({ Component: (await import('../features/training/public')).TrainingPage }) },
  { path: '/learner/records', role: 'learner', lazy: async () => ({ Component: (await import('../features/learner/public')).RecordsPage }) },
  { path: '/learner/support/:id', role: 'learner', lazy: async () => ({ Component: (await import('../features/support/public')).SupportPage }) },
  { path: '/counselor', role: 'counselor', lazy: async () => ({ Component: (await import('../features/counselor/public')).CounselorPage }) },
  { path: '/counselor/cases/:id', role: 'counselor', lazy: async () => ({ Component: (await import('../features/counselor/public')).CasePage }) },
  { path: '/counselor/sop/:id', role: 'counselor', lazy: async () => ({ Component: (await import('../features/sop/public')).SopPage }) },
  { path: '/counselor/submissions/:id', role: 'counselor', lazy: async () => ({ Component: (await import('../features/training/public')).FeedbackPage }) },
];
