"""Initial relational foundation with immutable training history."""
from alembic import op
revision = "0001_foundation"
down_revision = None
branch_labels = None
depends_on = None

DDL = (
    "CREATE TABLE jobs (\n\tkind VARCHAR(80) NOT NULL, \n\tpayload JSONB NOT NULL, \n\tdedupe_key VARCHAR(128) NOT NULL, \n\tstate VARCHAR(16) NOT NULL, \n\tattempts INTEGER NOT NULL, \n\tmax_attempts INTEGER NOT NULL, \n\tnext_run_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tlease_token UUID, \n\tlease_until TIMESTAMP WITH TIME ZONE, \n\terror_code VARCHAR(80), \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tCONSTRAINT pk_jobs PRIMARY KEY (id), \n\tCONSTRAINT ck_jobs_state CHECK (state IN ('pending','running','done','failed')), \n\tCONSTRAINT ck_jobs_attempts CHECK (attempts >= 0 AND max_attempts BETWEEN 1 AND 20), \n\tCONSTRAINT ck_jobs_lease CHECK ((state = 'running') = (lease_token IS NOT NULL AND lease_until IS NOT NULL)), \n\tCONSTRAINT uq_jobs_dedupe_key UNIQUE (dedupe_key)\n)",
    'CREATE INDEX ix_jobs_next_run_at ON jobs (next_run_at)',
    'CREATE TABLE users (\n\tlogin_name VARCHAR(80) NOT NULL, \n\tpassword_hash VARCHAR(255) NOT NULL, \n\tactive BOOLEAN NOT NULL, \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tCONSTRAINT pk_users PRIMARY KEY (id), \n\tCONSTRAINT uq_users_login_name UNIQUE (login_name)\n)',
    'CREATE TABLE audit_events (\n\tactor_id UUID, \n\taction VARCHAR(80) NOT NULL, \n\tresource_type VARCHAR(40) NOT NULL, \n\tresource_id UUID NOT NULL, \n\ttrace_id VARCHAR(128) NOT NULL, \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tCONSTRAINT pk_audit_events PRIMARY KEY (id), \n\tCONSTRAINT fk_audit_events_actor_id_users FOREIGN KEY(actor_id) REFERENCES users (id)\n)',
    "CREATE TABLE cases (\n\tlearner_id UUID NOT NULL, \n\tlifecycle VARCHAR(20) NOT NULL, \n\tversion INTEGER NOT NULL, \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tCONSTRAINT pk_cases PRIMARY KEY (id), \n\tCONSTRAINT ck_cases_lifecycle CHECK (lifecycle IN ('pending_match','active','closed')), \n\tCONSTRAINT ck_cases_version CHECK (version >= 1), \n\tCONSTRAINT fk_cases_learner_id_users FOREIGN KEY(learner_id) REFERENCES users (id)\n)",
    'CREATE INDEX ix_cases_learner_id ON cases (learner_id)',
    'CREATE TABLE external_identities (\n\tuser_id UUID NOT NULL, \n\tprovider VARCHAR(40) NOT NULL, \n\tsubject VARCHAR(255) NOT NULL, \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tCONSTRAINT pk_external_identities PRIMARY KEY (id), \n\tCONSTRAINT uq_external_identities_provider_subject UNIQUE (provider, subject), \n\tCONSTRAINT fk_external_identities_user_id_users FOREIGN KEY(user_id) REFERENCES users (id)\n)',
    'CREATE TABLE idempotency_records (\n\tactor_id UUID NOT NULL, \n\tmethod VARCHAR(8) NOT NULL, \n\tpath VARCHAR(255) NOT NULL, \n\tkey VARCHAR(128) NOT NULL, \n\tfingerprint VARCHAR(64) NOT NULL, \n\tresponse_status INTEGER, \n\tresponse_body JSONB, \n\tresponse_headers JSONB NOT NULL, \n\texpires_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tCONSTRAINT pk_idempotency_records PRIMARY KEY (id), \n\tCONSTRAINT uq_idempotency_scope UNIQUE (actor_id, method, path, key), \n\tCONSTRAINT fk_idempotency_records_actor_id_users FOREIGN KEY(actor_id) REFERENCES users (id)\n)',
    'CREATE INDEX ix_idempotency_records_expires_at ON idempotency_records (expires_at)',
    'CREATE TABLE notification_counters (\n\trecipient_id UUID NOT NULL, \n\tseq BIGINT NOT NULL, \n\tretained_after BIGINT NOT NULL, \n\tCONSTRAINT pk_notification_counters PRIMARY KEY (recipient_id), \n\tCONSTRAINT ck_notification_counters_sequence CHECK (seq >= retained_after AND retained_after >= 0), \n\tCONSTRAINT fk_notification_counters_recipient_id_users FOREIGN KEY(recipient_id) REFERENCES users (id)\n)',
    'CREATE TABLE notifications (\n\trecipient_id UUID NOT NULL, \n\tseq BIGINT NOT NULL, \n\tkind VARCHAR(80) NOT NULL, \n\tresource_type VARCHAR(40) NOT NULL, \n\tresource_id UUID NOT NULL, \n\tread_at TIMESTAMP WITH TIME ZONE, \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tCONSTRAINT pk_notifications PRIMARY KEY (id), \n\tCONSTRAINT uq_notifications_recipient_id_seq UNIQUE (recipient_id, seq), \n\tCONSTRAINT ck_notifications_sequence CHECK (seq > 0), \n\tCONSTRAINT fk_notifications_recipient_id_users FOREIGN KEY(recipient_id) REFERENCES users (id)\n)',
    'CREATE TABLE preferences (\n\tuser_id UUID NOT NULL, \n\tfont_scale FLOAT NOT NULL, \n\tvolume FLOAT NOT NULL, \n\tquiet_mode BOOLEAN NOT NULL, \n\tspeech_enabled BOOLEAN NOT NULL, \n\tvibration_enabled BOOLEAN NOT NULL, \n\tversion INTEGER NOT NULL, \n\tCONSTRAINT pk_preferences PRIMARY KEY (user_id), \n\tCONSTRAINT ck_preferences_font_scale CHECK (font_scale IN (1,1.25,1.5)), \n\tCONSTRAINT ck_preferences_volume CHECK (volume BETWEEN 0 AND 1), \n\tCONSTRAINT ck_preferences_version CHECK (version >= 1), \n\tCONSTRAINT fk_preferences_user_id_users FOREIGN KEY(user_id) REFERENCES users (id)\n)',
    'CREATE TABLE profiles (\n\tuser_id UUID NOT NULL, \n\tdisplay_name VARCHAR(80) NOT NULL, \n\tsensory_preferences JSONB NOT NULL, \n\tcommunication_preference VARCHAR(200) NOT NULL, \n\twork_notes VARCHAR(1000) NOT NULL, \n\tversion INTEGER NOT NULL, \n\tCONSTRAINT pk_profiles PRIMARY KEY (user_id), \n\tCONSTRAINT ck_profiles_version CHECK (version >= 1), \n\tCONSTRAINT fk_profiles_user_id_users FOREIGN KEY(user_id) REFERENCES users (id)\n)',
    'CREATE TABLE sessions (\n\tuser_id UUID, \n\ttoken_hash VARCHAR(64) NOT NULL, \n\tcsrf_hash VARCHAR(64) NOT NULL, \n\tlast_seen_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\texpires_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\trevoked_at TIMESTAMP WITH TIME ZONE, \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tCONSTRAINT pk_sessions PRIMARY KEY (id), \n\tCONSTRAINT fk_sessions_user_id_users FOREIGN KEY(user_id) REFERENCES users (id), \n\tCONSTRAINT uq_sessions_token_hash UNIQUE (token_hash)\n)',
    'CREATE INDEX ix_sessions_expires_at ON sessions (expires_at)',
    "CREATE TABLE user_roles (\n\tuser_id UUID NOT NULL, \n\trole VARCHAR(16) NOT NULL, \n\tCONSTRAINT pk_user_roles PRIMARY KEY (user_id, role), \n\tCONSTRAINT ck_user_roles_role CHECK (role IN ('learner','counselor')), \n\tCONSTRAINT fk_user_roles_user_id_users FOREIGN KEY(user_id) REFERENCES users (id)\n)",
    'CREATE TABLE case_grants (\n\tcase_id UUID NOT NULL, \n\tcounselor_id UUID NOT NULL, \n\trevoked_at TIMESTAMP WITH TIME ZONE, \n\tCONSTRAINT pk_case_grants PRIMARY KEY (case_id, counselor_id), \n\tCONSTRAINT fk_case_grants_case_id_cases FOREIGN KEY(case_id) REFERENCES cases (id), \n\tCONSTRAINT fk_case_grants_counselor_id_users FOREIGN KEY(counselor_id) REFERENCES users (id)\n)',
    'CREATE TABLE sop_plans (\n\tcase_id UUID NOT NULL, \n\ttitle VARCHAR(120) NOT NULL, \n\tauthor_id UUID NOT NULL, \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tCONSTRAINT pk_sop_plans PRIMARY KEY (id), \n\tCONSTRAINT uq_sop_plans_id_case_id UNIQUE (id, case_id), \n\tCONSTRAINT fk_sop_plans_case_id_cases FOREIGN KEY(case_id) REFERENCES cases (id), \n\tCONSTRAINT fk_sop_plans_author_id_users FOREIGN KEY(author_id) REFERENCES users (id)\n)',
    'CREATE INDEX ix_sop_plans_case_id ON sop_plans (case_id)',
    "CREATE TABLE support_matches (\n\tcase_id UUID NOT NULL, \n\tdirection VARCHAR(80) NOT NULL, \n\tfocus VARCHAR(500) NOT NULL, \n\tbasis VARCHAR(1000) NOT NULL, \n\tcycle_weeks INTEGER NOT NULL, \n\tstate VARCHAR(16) NOT NULL, \n\tversion INTEGER NOT NULL, \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tCONSTRAINT pk_support_matches PRIMARY KEY (id), \n\tCONSTRAINT ck_support_matches_state CHECK (state IN ('draft','confirmed')), \n\tCONSTRAINT ck_support_matches_cycle CHECK (cycle_weeks BETWEEN 1 AND 52), \n\tCONSTRAINT ck_support_matches_version CHECK (version >= 1), \n\tCONSTRAINT uq_support_matches_id_case_id UNIQUE (id, case_id), \n\tCONSTRAINT uq_support_matches_case_id UNIQUE (case_id), \n\tCONSTRAINT fk_support_matches_case_id_cases FOREIGN KEY(case_id) REFERENCES cases (id)\n)",
    "CREATE TABLE sop_revisions (\n\tplan_id UUID NOT NULL, \n\tcase_id UUID NOT NULL, \n\tnumber INTEGER NOT NULL, \n\tstate VARCHAR(16) NOT NULL, \n\tgoal VARCHAR(1000) NOT NULL, \n\treminder JSONB NOT NULL, \n\tschema_version INTEGER NOT NULL, \n\tversion INTEGER NOT NULL, \n\tpublished_at TIMESTAMP WITH TIME ZONE, \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tCONSTRAINT pk_sop_revisions PRIMARY KEY (id), \n\tCONSTRAINT fk_sop_revisions_plan_id_case_id_sop_plans FOREIGN KEY(plan_id, case_id) REFERENCES sop_plans (id, case_id), \n\tCONSTRAINT uq_sop_revisions_plan_id_number UNIQUE (plan_id, number), \n\tCONSTRAINT uq_sop_revisions_id_case_id UNIQUE (id, case_id), \n\tCONSTRAINT ck_sop_revisions_state CHECK (state IN ('draft','published')), \n\tCONSTRAINT ck_sop_revisions_versions CHECK (number >= 1 AND version >= 1 AND schema_version >= 1), \n\tCONSTRAINT ck_sop_revisions_publication CHECK ((state = 'published') = (published_at IS NOT NULL))\n)",
    "CREATE UNIQUE INDEX uq_sop_current_draft ON sop_revisions (plan_id) WHERE state = 'draft'",
    'CREATE TABLE sop_steps (\n\trevision_id UUID NOT NULL, \n\tid UUID NOT NULL, \n\tposition INTEGER NOT NULL, \n\tinstruction VARCHAR(2000) NOT NULL, \n\tmedia_ids JSONB NOT NULL, \n\tevidence_required BOOLEAN NOT NULL, \n\testimated_seconds INTEGER, \n\tCONSTRAINT pk_sop_steps PRIMARY KEY (revision_id, id), \n\tCONSTRAINT uq_sop_steps_revision_id_position UNIQUE (revision_id, position), \n\tCONSTRAINT ck_sop_steps_position CHECK (position BETWEEN 1 AND 100), \n\tCONSTRAINT ck_sop_steps_duration CHECK (estimated_seconds IS NULL OR estimated_seconds >= 1), \n\tCONSTRAINT fk_sop_steps_revision_id_sop_revisions FOREIGN KEY(revision_id) REFERENCES sop_revisions (id)\n)',
    "CREATE TABLE training_tasks (\n\tcase_id UUID NOT NULL, \n\trevision_id UUID NOT NULL, \n\tstatus VARCHAR(24) NOT NULL, \n\tdue_on DATE, \n\tprompt_override INTEGER, \n\tversion INTEGER NOT NULL, \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tCONSTRAINT pk_training_tasks PRIMARY KEY (id), \n\tCONSTRAINT fk_training_tasks_revision_id_case_id_sop_revisions FOREIGN KEY(revision_id, case_id) REFERENCES sop_revisions (id, case_id), \n\tCONSTRAINT uq_training_tasks_id_revision_id UNIQUE (id, revision_id), \n\tCONSTRAINT uq_training_tasks_id_case_id UNIQUE (id, case_id), \n\tCONSTRAINT ck_training_tasks_status CHECK (status IN ('not_started','in_progress','paused','submitted','changes_requested','completed','cancelled')), \n\tCONSTRAINT ck_training_tasks_version CHECK (version >= 1), \n\tCONSTRAINT ck_training_tasks_prompt CHECK (prompt_override IS NULL OR prompt_override BETWEEN 0 AND 3), \n\tCONSTRAINT fk_training_tasks_case_id_cases FOREIGN KEY(case_id) REFERENCES cases (id), \n\tCONSTRAINT uq_training_tasks_revision_id UNIQUE (revision_id)\n)",
    "CREATE UNIQUE INDEX uq_case_active_task ON training_tasks (case_id) WHERE status NOT IN ('completed','cancelled')",
    "CREATE TABLE assistance_requests (\n\tcase_id UUID NOT NULL, \n\ttask_id UUID, \n\tstep_id UUID, \n\trevision_id UUID, \n\tstate VARCHAR(16) NOT NULL, \n\tmessage VARCHAR(500) NOT NULL, \n\tattachment_ids JSONB NOT NULL, \n\tpreferred_mode VARCHAR(16) NOT NULL, \n\tversion INTEGER NOT NULL, \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tCONSTRAINT pk_assistance_requests PRIMARY KEY (id), \n\tCONSTRAINT fk_assistance_requests_task_id_case_id_training_tasks FOREIGN KEY(task_id, case_id) REFERENCES training_tasks (id, case_id), \n\tCONSTRAINT ck_assistance_requests_state CHECK (state IN ('queued','accepted','resolved','cancelled')), \n\tCONSTRAINT ck_assistance_requests_step_context CHECK (step_id IS NULL OR task_id IS NOT NULL), \n\tCONSTRAINT ck_assistance_requests_revision_context CHECK ((task_id IS NULL) = (revision_id IS NULL)), \n\tCONSTRAINT fk_assistance_requests_task_id_revision_id_training_tasks FOREIGN KEY(task_id, revision_id) REFERENCES training_tasks (id, revision_id), \n\tCONSTRAINT fk_assistance_requests_revision_id_step_id_sop_steps FOREIGN KEY(revision_id, step_id) REFERENCES sop_steps (revision_id, id), \n\tCONSTRAINT ck_assistance_requests_mode CHECK (preferred_mode IN ('text','annotation')), \n\tCONSTRAINT ck_assistance_requests_version CHECK (version >= 1), \n\tCONSTRAINT fk_assistance_requests_case_id_cases FOREIGN KEY(case_id) REFERENCES cases (id)\n)",
    "CREATE UNIQUE INDEX uq_open_assistance ON assistance_requests (case_id, task_id) NULLS NOT DISTINCT WHERE state IN ('queued','accepted')",
    "CREATE TABLE file_assets (\n\tcase_id UUID NOT NULL, \n\ttask_id UUID, \n\tuploader_id UUID NOT NULL, \n\tpurpose VARCHAR(24) NOT NULL, \n\tstorage_key VARCHAR(255) NOT NULL, \n\tfilename VARCHAR(255) NOT NULL, \n\tmime_type VARCHAR(128) NOT NULL, \n\tsize_bytes BIGINT NOT NULL, \n\tsha256 VARCHAR(64) NOT NULL, \n\tstate VARCHAR(16) NOT NULL, \n\twidth INTEGER, \n\theight INTEGER, \n\treason VARCHAR(200), \n\tversion INTEGER NOT NULL, \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tCONSTRAINT pk_file_assets PRIMARY KEY (id), \n\tCONSTRAINT uq_file_assets_id_case_id UNIQUE (id, case_id), \n\tCONSTRAINT fk_file_assets_task_id_case_id_training_tasks FOREIGN KEY(task_id, case_id) REFERENCES training_tasks (id, case_id), \n\tCONSTRAINT ck_file_assets_state CHECK (state IN ('quarantined','scanning','ready','rejected','deleted')), \n\tCONSTRAINT ck_file_assets_purpose CHECK (purpose IN ('profile_material','task_evidence','sop_media','support_message')), \n\tCONSTRAINT ck_file_assets_bounds CHECK (size_bytes BETWEEN 1 AND 20971520 AND version >= 1), \n\tCONSTRAINT fk_file_assets_case_id_cases FOREIGN KEY(case_id) REFERENCES cases (id), \n\tCONSTRAINT fk_file_assets_uploader_id_users FOREIGN KEY(uploader_id) REFERENCES users (id), \n\tCONSTRAINT uq_file_assets_storage_key UNIQUE (storage_key)\n)",
    "CREATE TABLE step_progress (\n\ttask_id UUID NOT NULL, \n\tstep_id UUID NOT NULL, \n\trevision_id UUID NOT NULL, \n\tstatus VARCHAR(16) NOT NULL, \n\tattachment_ids JSONB NOT NULL, \n\tCONSTRAINT pk_step_progress PRIMARY KEY (task_id, step_id), \n\tCONSTRAINT fk_step_progress_task_id_revision_id_training_tasks FOREIGN KEY(task_id, revision_id) REFERENCES training_tasks (id, revision_id), \n\tCONSTRAINT fk_step_progress_revision_id_step_id_sop_steps FOREIGN KEY(revision_id, step_id) REFERENCES sop_steps (revision_id, id), \n\tCONSTRAINT ck_step_progress_status CHECK (status IN ('pending','in_progress','completed'))\n)",
    'CREATE TABLE submissions (\n\ttask_id UUID NOT NULL, \n\tattempt_no INTEGER NOT NULL, \n\tschema_version INTEGER NOT NULL, \n\tsnapshot JSONB NOT NULL, \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tCONSTRAINT pk_submissions PRIMARY KEY (id), \n\tCONSTRAINT uq_submissions_task_id_attempt_no UNIQUE (task_id, attempt_no), \n\tCONSTRAINT uq_submissions_id_task_id UNIQUE (id, task_id), \n\tCONSTRAINT ck_submissions_versions CHECK (attempt_no >= 1 AND schema_version >= 1), \n\tCONSTRAINT fk_submissions_task_id_training_tasks FOREIGN KEY(task_id) REFERENCES training_tasks (id)\n)',
    'CREATE INDEX ix_submissions_task_id ON submissions (task_id)',
    "CREATE TABLE task_events (\n\ttask_id UUID NOT NULL, \n\tevent_id UUID NOT NULL, \n\trevision_id UUID NOT NULL, \n\tsession_id UUID NOT NULL, \n\tstep_id UUID NOT NULL, \n\tsequence INTEGER NOT NULL, \n\tkind VARCHAR(32) NOT NULL, \n\tvalue INTEGER, \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tCONSTRAINT pk_task_events PRIMARY KEY (id), \n\tCONSTRAINT fk_task_events_task_id_revision_id_training_tasks FOREIGN KEY(task_id, revision_id) REFERENCES training_tasks (id, revision_id), \n\tCONSTRAINT fk_task_events_revision_id_step_id_sop_steps FOREIGN KEY(revision_id, step_id) REFERENCES sop_steps (revision_id, id), \n\tCONSTRAINT ck_task_events_kind CHECK (kind IN ('hint_requested','self_reported_error','time_sample')), \n\tCONSTRAINT ck_task_events_values CHECK (sequence >= 0 AND (value IS NULL OR value >= 0)), \n\tCONSTRAINT fk_task_events_task_id_training_tasks FOREIGN KEY(task_id) REFERENCES training_tasks (id), \n\tCONSTRAINT uq_task_events_event_id UNIQUE (event_id)\n)",
    'CREATE INDEX ix_task_events_task_id ON task_events (task_id)',
    "CREATE TABLE annotations (\n\tcase_id UUID NOT NULL, \n\ttask_id UUID NOT NULL, \n\tasset_id UUID NOT NULL, \n\tsubmission_id UUID, \n\tauthor_id UUID NOT NULL, \n\tkind VARCHAR(16) NOT NULL, \n\tstate VARCHAR(16) NOT NULL, \n\tmarkers JSONB NOT NULL, \n\tversion INTEGER NOT NULL, \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tCONSTRAINT pk_annotations PRIMARY KEY (id), \n\tCONSTRAINT fk_annotations_task_id_case_id_training_tasks FOREIGN KEY(task_id, case_id) REFERENCES training_tasks (id, case_id), \n\tCONSTRAINT fk_annotations_asset_id_case_id_file_assets FOREIGN KEY(asset_id, case_id) REFERENCES file_assets (id, case_id), \n\tCONSTRAINT fk_annotations_submission_id_task_id_submissions FOREIGN KEY(submission_id, task_id) REFERENCES submissions (id, task_id), \n\tCONSTRAINT ck_annotations_kind CHECK (kind IN ('question','guidance')), \n\tCONSTRAINT ck_annotations_state CHECK (state IN ('draft','published')), \n\tCONSTRAINT ck_annotations_version CHECK (version >= 1), \n\tCONSTRAINT fk_annotations_case_id_cases FOREIGN KEY(case_id) REFERENCES cases (id), \n\tCONSTRAINT fk_annotations_author_id_users FOREIGN KEY(author_id) REFERENCES users (id)\n)",
    "CREATE TABLE feedback (\n\tsubmission_id UUID NOT NULL, \n\tauthor_id UUID NOT NULL, \n\toutcome VARCHAR(24) NOT NULL, \n\tmessage VARCHAR(500) NOT NULL, \n\tredo_step_ids JSONB NOT NULL, \n\tannotation_ids JSONB NOT NULL, \n\ttags JSONB NOT NULL, \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tCONSTRAINT pk_feedback PRIMARY KEY (id), \n\tCONSTRAINT ck_feedback_outcome CHECK (outcome IN ('passed','changes_requested')), \n\tCONSTRAINT ck_feedback_message CHECK (length(trim(message)) > 0), \n\tCONSTRAINT ck_feedback_redo CHECK ((outcome = 'changes_requested') = (jsonb_array_length(redo_step_ids) > 0)), \n\tCONSTRAINT uq_feedback_submission_id UNIQUE (submission_id), \n\tCONSTRAINT fk_feedback_submission_id_submissions FOREIGN KEY(submission_id) REFERENCES submissions (id), \n\tCONSTRAINT fk_feedback_author_id_users FOREIGN KEY(author_id) REFERENCES users (id)\n)",
    "CREATE TABLE file_links (\n\tasset_id UUID NOT NULL, \n\tcase_id UUID NOT NULL, \n\towner_kind VARCHAR(24) NOT NULL, \n\towner_id UUID NOT NULL, \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tCONSTRAINT pk_file_links PRIMARY KEY (id), \n\tCONSTRAINT fk_file_links_asset_id_case_id_file_assets FOREIGN KEY(asset_id, case_id) REFERENCES file_assets (id, case_id), \n\tCONSTRAINT uq_file_links_asset_id_owner_kind_owner_id UNIQUE (asset_id, owner_kind, owner_id), \n\tCONSTRAINT ck_file_links_owner_kind CHECK (owner_kind IN ('sop_revision','submission','support_message','annotation')), \n\tCONSTRAINT fk_file_links_case_id_cases FOREIGN KEY(case_id) REFERENCES cases (id)\n)",
    'CREATE TABLE support_messages (\n\trequest_id UUID NOT NULL, \n\tauthor_id UUID NOT NULL, \n\tbody VARCHAR(2000) NOT NULL, \n\tattachment_ids JSONB NOT NULL, \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tCONSTRAINT pk_support_messages PRIMARY KEY (id), \n\tCONSTRAINT ck_support_messages_content CHECK (length(trim(body)) > 0 OR jsonb_array_length(attachment_ids) > 0), \n\tCONSTRAINT fk_support_messages_request_id_assistance_requests FOREIGN KEY(request_id) REFERENCES assistance_requests (id), \n\tCONSTRAINT fk_support_messages_author_id_users FOREIGN KEY(author_id) REFERENCES users (id)\n)',
    'CREATE INDEX ix_support_messages_request_id ON support_messages (request_id)',
    "CREATE FUNCTION jl_append_only() RETURNS trigger LANGUAGE plpgsql AS $$\nBEGIN\n  RAISE EXCEPTION 'immutable history: %', TG_TABLE_NAME USING ERRCODE = '23514';\nEND $$",
    'CREATE TRIGGER immutable_submissions BEFORE UPDATE OR DELETE ON submissions FOR EACH ROW EXECUTE FUNCTION jl_append_only()',
    'CREATE TRIGGER immutable_feedback BEFORE UPDATE OR DELETE ON feedback FOR EACH ROW EXECUTE FUNCTION jl_append_only()',
    'CREATE TRIGGER immutable_support_messages BEFORE UPDATE OR DELETE ON support_messages FOR EACH ROW EXECUTE FUNCTION jl_append_only()',
    'CREATE TRIGGER immutable_audit_events BEFORE UPDATE OR DELETE ON audit_events FOR EACH ROW EXECUTE FUNCTION jl_append_only()',
    "CREATE FUNCTION jl_frozen_state() RETURNS trigger LANGUAGE plpgsql AS $$\nBEGIN\n  IF OLD.state IN ('published','confirmed') THEN\n    RAISE EXCEPTION 'immutable published resource: %', TG_TABLE_NAME USING ERRCODE = '23514';\n  END IF;\n  IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;\n  RETURN NEW;\nEND $$",
    'CREATE TRIGGER frozen_sop_revisions BEFORE UPDATE OR DELETE ON sop_revisions FOR EACH ROW EXECUTE FUNCTION jl_frozen_state()',
    'CREATE TRIGGER frozen_annotations BEFORE UPDATE OR DELETE ON annotations FOR EACH ROW EXECUTE FUNCTION jl_frozen_state()',
    'CREATE TRIGGER frozen_support_matches BEFORE UPDATE OR DELETE ON support_matches FOR EACH ROW EXECUTE FUNCTION jl_frozen_state()',
    "CREATE FUNCTION jl_step_guard() RETURNS trigger LANGUAGE plpgsql AS $$\nDECLARE old_state text; new_state text;\nBEGIN\n  IF TG_OP <> 'INSERT' THEN\n    SELECT state INTO old_state FROM sop_revisions WHERE id = OLD.revision_id FOR UPDATE;\n    IF old_state = 'published' THEN RAISE EXCEPTION 'published step is immutable' USING ERRCODE = '23514'; END IF;\n  END IF;\n  IF TG_OP <> 'DELETE' THEN\n    SELECT state INTO new_state FROM sop_revisions WHERE id = NEW.revision_id FOR UPDATE;\n    IF new_state = 'published' THEN RAISE EXCEPTION 'cannot add or move a step into a published revision' USING ERRCODE = '23514'; END IF;\n    RETURN NEW;\n  END IF;\n  RETURN OLD;\nEND $$",
    'CREATE TRIGGER frozen_sop_steps BEFORE INSERT OR UPDATE OR DELETE ON sop_steps FOR EACH ROW EXECUTE FUNCTION jl_step_guard()',
)

def upgrade() -> None:
    for statement in DDL:
        op.execute(statement)

def downgrade() -> None:
    op.execute("DROP TABLE support_messages")
    op.execute("DROP TABLE file_links")
    op.execute("DROP TABLE feedback")
    op.execute("DROP TABLE annotations")
    op.execute("DROP TABLE task_events")
    op.execute("DROP TABLE submissions")
    op.execute("DROP TABLE step_progress")
    op.execute("DROP TABLE file_assets")
    op.execute("DROP TABLE assistance_requests")
    op.execute("DROP TABLE training_tasks")
    op.execute("DROP TABLE sop_steps")
    op.execute("DROP TABLE sop_revisions")
    op.execute("DROP TABLE support_matches")
    op.execute("DROP TABLE sop_plans")
    op.execute("DROP TABLE case_grants")
    op.execute("DROP TABLE user_roles")
    op.execute("DROP TABLE sessions")
    op.execute("DROP TABLE profiles")
    op.execute("DROP TABLE preferences")
    op.execute("DROP TABLE notifications")
    op.execute("DROP TABLE notification_counters")
    op.execute("DROP TABLE idempotency_records")
    op.execute("DROP TABLE external_identities")
    op.execute("DROP TABLE cases")
    op.execute("DROP TABLE audit_events")
    op.execute("DROP TABLE users")
    op.execute("DROP TABLE jobs")
    op.execute("DROP FUNCTION jl_step_guard()")
    op.execute("DROP FUNCTION jl_frozen_state()")
    op.execute("DROP FUNCTION jl_append_only()")
