# Generated by tools/generate_http_models.py from contracts/openapi.yaml.
# Do not edit: domain decisions stay in module rules/services.
from datetime import date, datetime
from typing import Annotated, Any, Literal
from uuid import UUID

from fastapi import UploadFile
from pydantic import BaseModel, BeforeValidator, ConfigDict, Field, WithJsonSchema

from app.web.schemas import Preferences


def omit_default(schema: dict[str, Any]) -> None:
    schema.pop("default", None)


def reject_null(value: Any) -> Any:
    if value is None:
        raise ValueError("explicit null is not allowed")
    return value


class CaseProfile(BaseModel):
    model_config = ConfigDict(extra="forbid", from_attributes=True)
    display_name: Annotated[str, Field(min_length=1, max_length=80)]
    sensory_preferences: Annotated[list[Annotated[str, Field(min_length=1, max_length=40)]], Field(max_length=10)]
    communication_preference: Annotated[str, Field(max_length=200)]
    work_notes: Annotated[str, Field(max_length=1000)]
    user_id: UUID
    version: Annotated[int, Field(ge=1, le=2147483647)]
    preferences: Preferences


class Dashboard(BaseModel):
    model_config = ConfigDict(extra="forbid", from_attributes=True)
    view: Literal['learner', 'counselor']
    pending_tasks: Annotated[int, Field(ge=0, le=2147483647)]
    pending_feedback: Annotated[int, Field(ge=0, le=2147483647)]
    pending_assistance: Annotated[int, Field(ge=0, le=2147483647)]
    as_of: datetime


class Case(BaseModel):
    model_config = ConfigDict(extra="forbid", from_attributes=True)
    id: UUID
    learner_id: UUID
    counselor_id: Annotated[UUID | None, WithJsonSchema({'type': ['string', 'null'], 'format': 'uuid'})]
    lifecycle: Literal['pending_match', 'active', 'closed']
    display_status: Literal['pending_match', 'sop_pending', 'training', 'awaiting_feedback', 'feedback_available', 'stage_complete', 'closed']
    current_task_id: Annotated[UUID | None, WithJsonSchema({'type': ['string', 'null'], 'format': 'uuid'})]
    version: Annotated[int, Field(ge=1, le=2147483647)]


class MatchWrite(BaseModel):
    model_config = ConfigDict(extra="forbid", from_attributes=True)
    direction: Annotated[str, Field(max_length=80)]
    focus: Annotated[str, Field(max_length=500)]
    cycle_weeks: Annotated[int, Field(ge=1, le=52)]
    basis: Annotated[str, Field(max_length=1000)]


class SupportMatch(BaseModel):
    model_config = ConfigDict(extra="forbid", from_attributes=True)
    direction: Annotated[str, Field(max_length=80)]
    focus: Annotated[str, Field(max_length=500)]
    cycle_weeks: Annotated[int, Field(ge=1, le=52)]
    basis: Annotated[str, Field(max_length=1000)]
    id: UUID
    case_id: UUID
    state: Literal['draft', 'confirmed']
    version: Annotated[int, Field(ge=1, le=2147483647)]


class FileUpload(BaseModel):
    model_config = ConfigDict(extra="forbid", from_attributes=True)
    case_id: UUID
    task_id: Annotated[UUID | None, BeforeValidator(reject_null), WithJsonSchema({'type': 'string', 'format': 'uuid'})] = Field(default=None, json_schema_extra=omit_default)
    purpose: Literal['profile_material', 'task_evidence', 'sop_media', 'support_message']
    file: Annotated[UploadFile, WithJsonSchema({'type': 'string', 'format': 'binary'})]


class FileAsset(BaseModel):
    model_config = ConfigDict(extra="forbid", from_attributes=True)
    id: UUID
    case_id: UUID
    task_id: Annotated[UUID | None, WithJsonSchema({'type': ['string', 'null'], 'format': 'uuid'})]
    purpose: Literal['profile_material', 'task_evidence', 'sop_media', 'support_message']
    filename: Annotated[str, Field(min_length=1, max_length=255)]
    mime_type: Annotated[str, Field(min_length=1, max_length=128)]
    size_bytes: Annotated[int, Field(ge=1, le=20971520)]
    state: Literal['quarantined', 'scanning', 'ready', 'rejected', 'deleted']
    reason: Annotated[Annotated[str | None, WithJsonSchema({'type': ['string', 'null'], 'maxLength': 200})], Field(max_length=200)]
    width: Annotated[Annotated[int | None, WithJsonSchema({'type': ['integer', 'null'], 'minimum': 1, 'maximum': 20000})], Field(ge=1, le=20000)]
    height: Annotated[Annotated[int | None, WithJsonSchema({'type': ['integer', 'null'], 'minimum': 1, 'maximum': 20000})], Field(ge=1, le=20000)]
    version: Annotated[int, Field(ge=1, le=2147483647)]
    created_at: datetime


class PlanCreate(BaseModel):
    model_config = ConfigDict(extra="forbid", from_attributes=True)
    title: Annotated[str, Field(min_length=1, max_length=120)]


class SopPlan(BaseModel):
    model_config = ConfigDict(extra="forbid", from_attributes=True)
    id: UUID
    case_id: UUID
    title: Annotated[str, Field(min_length=1, max_length=120)]
    published_revision_id: Annotated[UUID | None, WithJsonSchema({'type': ['string', 'null'], 'format': 'uuid'})]
    draft_revision_id: Annotated[UUID | None, WithJsonSchema({'type': ['string', 'null'], 'format': 'uuid'})]
    version: Annotated[int, Field(ge=1, le=2147483647)]


class RevisionCreate(BaseModel):
    model_config = ConfigDict(extra="forbid", from_attributes=True)
    base_revision_id: Annotated[UUID | None, WithJsonSchema({'type': ['string', 'null'], 'format': 'uuid'})] = Field(default=None, json_schema_extra=omit_default)


class Reminder(BaseModel):
    model_config = ConfigDict(extra="forbid", from_attributes=True)
    speech_enabled: bool
    vibration_enabled: bool
    prompt_level: Annotated[int, Field(ge=1, le=3)]


class SopStep(BaseModel):
    model_config = ConfigDict(extra="forbid", from_attributes=True)
    id: UUID
    position: Annotated[int, Field(ge=1, le=100)]
    instruction: Annotated[str, Field(max_length=2000)]
    media_ids: Annotated[list[UUID], Field(max_length=5)]
    estimated_seconds: Annotated[int, Field(ge=0, le=86400)]
    evidence_required: bool


class RevisionWrite(BaseModel):
    model_config = ConfigDict(extra="forbid", from_attributes=True)
    goal: Annotated[str, Field(max_length=1000)]
    steps: Annotated[list[SopStep], Field(max_length=100)]
    reminder: Reminder


class SopRevision(BaseModel):
    model_config = ConfigDict(extra="forbid", from_attributes=True)
    goal: Annotated[str, Field(max_length=1000)]
    steps: Annotated[list[SopStep], Field(max_length=100)]
    reminder: Reminder
    id: UUID
    plan_id: UUID
    revision_no: Annotated[int, Field(ge=1, le=2147483647)]
    state: Literal['draft', 'published', 'archived']
    version: Annotated[int, Field(ge=1, le=2147483647)]
    published_at: Annotated[datetime | None, WithJsonSchema({'type': ['string', 'null'], 'format': 'date-time'})]


class PublishRequest(BaseModel):
    model_config = ConfigDict(extra="forbid", from_attributes=True)
    due_on: Annotated[date | None, WithJsonSchema({'type': ['string', 'null'], 'format': 'date'})]


class Publication(BaseModel):
    model_config = ConfigDict(extra="forbid", from_attributes=True)
    revision_id: UUID
    task_id: UUID
    published_at: datetime


class StepProgress(BaseModel):
    model_config = ConfigDict(extra="forbid", from_attributes=True)
    step_id: UUID
    status: Literal['pending', 'in_progress', 'completed']
    attachment_ids: Annotated[list[UUID], Field(max_length=5)]


class PromptOverrideWrite(BaseModel):
    model_config = ConfigDict(extra="forbid", from_attributes=True)
    prompt_level: Annotated[int, Field(ge=1, le=3)]
    reason: Annotated[str, Field(min_length=1, max_length=500)]


class Task(BaseModel):
    model_config = ConfigDict(extra="forbid", from_attributes=True)
    id: UUID
    case_id: UUID
    learner_id: UUID
    title: Annotated[str, Field(min_length=1, max_length=120)]
    revision: SopRevision
    status: Literal['not_started', 'in_progress', 'paused', 'submitted', 'changes_requested', 'completed', 'cancelled']
    due_on: Annotated[date | None, WithJsonSchema({'type': ['string', 'null'], 'format': 'date'})]
    current_step_id: Annotated[UUID | None, WithJsonSchema({'type': ['string', 'null'], 'format': 'uuid'})]
    progress: Annotated[list[StepProgress], Field(max_length=100)]
    prompt_override: PromptOverrideWrite | None
    version: Annotated[int, Field(ge=1, le=2147483647)]


class TaskAction(BaseModel):
    model_config = ConfigDict(extra="forbid", from_attributes=True, json_schema_extra={'allOf': [{'if': {'properties': {'action': {'const': 'cancel'}}}, 'then': {'required': ['reason'], 'properties': {'reason': {'minLength': 1, 'pattern': '\\S'}}}}]})
    action: Literal['start', 'pause', 'resume', 'cancel']
    reason: Annotated[Annotated[str, Field(max_length=500)] | None, BeforeValidator(reject_null), WithJsonSchema({'type': 'string', 'maxLength': 500})] = Field(default=None, json_schema_extra=omit_default)


class ProgressWrite(BaseModel):
    model_config = ConfigDict(extra="forbid", from_attributes=True)
    status: Literal['in_progress', 'completed']
    attachment_ids: Annotated[list[UUID], Field(max_length=5)]


class TaskEvent(BaseModel):
    model_config = ConfigDict(extra="forbid", from_attributes=True)
    event_id: UUID
    session_id: UUID
    sequence: Annotated[int, Field(ge=1, le=2147483647)]
    step_id: UUID
    kind: Literal['hint_requested', 'self_reported_error', 'time_sample']
    value: Annotated[int, Field(ge=0, le=86400000)]
    observed_at: datetime


class EventBatch(BaseModel):
    model_config = ConfigDict(extra="forbid", from_attributes=True)
    events: Annotated[list[TaskEvent], Field(min_length=1, max_length=100)]


class EventReceipt(BaseModel):
    model_config = ConfigDict(extra="forbid", from_attributes=True)
    accepted: Annotated[int, Field(ge=0, le=100)]
    duplicates: Annotated[int, Field(ge=0, le=100)]


class SubmissionCreate(BaseModel):
    model_config = ConfigDict(extra="forbid", from_attributes=True)
    note: Annotated[str, Field(max_length=500)]


class SubmissionSnapshot(BaseModel):
    model_config = ConfigDict(extra="forbid", from_attributes=True)
    schema_version: Literal[1]
    revision_id: UUID
    progress: Annotated[list[StepProgress], Field(max_length=100)]


class FeedbackCreate(BaseModel):
    model_config = ConfigDict(extra="forbid", from_attributes=True, json_schema_extra={'allOf': [{'if': {'properties': {'outcome': {'const': 'changes_requested'}}}, 'then': {'properties': {'redo_step_ids': {'minItems': 1}}}, 'else': {'properties': {'redo_step_ids': {'maxItems': 0}}}}]})
    outcome: Literal['passed', 'changes_requested']
    message: Annotated[str, Field(min_length=1, max_length=500)]
    tags: Annotated[list[Literal['title_correct', 'naming_adjustment', 'retake_required', 'other']], Field(max_length=5)]
    redo_step_ids: Annotated[list[UUID], Field(max_length=100)]
    annotation_ids: Annotated[list[UUID], Field(max_length=20)]


class Feedback(BaseModel):
    model_config = ConfigDict(extra="forbid", from_attributes=True, json_schema_extra={'allOf': [{'if': {'properties': {'outcome': {'const': 'changes_requested'}}}, 'then': {'properties': {'redo_step_ids': {'minItems': 1}}}, 'else': {'properties': {'redo_step_ids': {'maxItems': 0}}}}]})
    outcome: Literal['passed', 'changes_requested']
    message: Annotated[str, Field(min_length=1, max_length=500)]
    tags: Annotated[list[Literal['title_correct', 'naming_adjustment', 'retake_required', 'other']], Field(max_length=5)]
    redo_step_ids: Annotated[list[UUID], Field(max_length=100)]
    annotation_ids: Annotated[list[UUID], Field(max_length=20)]
    id: UUID
    submission_id: UUID
    author_id: UUID
    created_at: datetime


class Submission(BaseModel):
    model_config = ConfigDict(extra="forbid", from_attributes=True)
    id: UUID
    task_id: UUID
    attempt_no: Annotated[int, Field(ge=1, le=2147483647)]
    revision_id: UUID
    note: Annotated[str, Field(max_length=500)]
    snapshot: SubmissionSnapshot
    submitted_at: datetime
    task_version: Annotated[int, Field(ge=1, le=2147483647)]
    task_status: Literal['not_started', 'in_progress', 'paused', 'submitted', 'changes_requested', 'completed', 'cancelled']
    feedback: Feedback | None


class FeedbackResult(BaseModel):
    model_config = ConfigDict(extra="forbid", from_attributes=True)
    feedback: Feedback
    task: Task


class PointMarker(BaseModel):
    model_config = ConfigDict(extra="forbid", from_attributes=True)
    id: UUID
    x: Annotated[float, Field(ge=0, le=1)]
    y: Annotated[float, Field(ge=0, le=1)]
    text: Annotated[str, Field(min_length=1, max_length=200)]
    shape: Literal['point']


class RectMarker(BaseModel):
    model_config = ConfigDict(extra="forbid", from_attributes=True)
    id: UUID
    x: Annotated[float, Field(ge=0, le=1)]
    y: Annotated[float, Field(ge=0, le=1)]
    text: Annotated[str, Field(min_length=1, max_length=200)]
    shape: Literal['rect']
    width: Annotated[float, Field(le=1, gt=0)]
    height: Annotated[float, Field(le=1, gt=0)]


type Marker = Annotated[PointMarker | RectMarker, Field(discriminator='shape')]


class AnnotationCreate(BaseModel):
    model_config = ConfigDict(extra="forbid", from_attributes=True)
    asset_id: UUID
    submission_id: Annotated[UUID | None, WithJsonSchema({'type': ['string', 'null'], 'format': 'uuid'})]
    kind: Literal['question', 'guidance']
    markers: Annotated[list[Marker], Field(min_length=1, max_length=100)]


class AnnotationWrite(BaseModel):
    model_config = ConfigDict(extra="forbid", from_attributes=True)
    markers: Annotated[list[Marker], Field(min_length=1, max_length=100)]


class Annotation(BaseModel):
    model_config = ConfigDict(extra="forbid", from_attributes=True)
    id: UUID
    task_id: UUID
    submission_id: Annotated[UUID | None, WithJsonSchema({'type': ['string', 'null'], 'format': 'uuid'})]
    asset_id: UUID
    author_id: UUID
    kind: Literal['question', 'guidance']
    markers: Annotated[list[Marker], Field(min_length=1, max_length=100)]
    state: Literal['draft', 'published']
    version: Annotated[int, Field(ge=1, le=2147483647)]


class AssistanceCreate(BaseModel):
    model_config = ConfigDict(extra="forbid", from_attributes=True)
    case_id: UUID
    task_id: Annotated[UUID | None, WithJsonSchema({'type': ['string', 'null'], 'format': 'uuid'})]
    step_id: Annotated[UUID | None, WithJsonSchema({'type': ['string', 'null'], 'format': 'uuid'})]
    message: Annotated[str, Field(min_length=1, max_length=500)]
    attachment_ids: Annotated[list[UUID], Field(max_length=5)]
    preferred_mode: Literal['text', 'annotation']


class Assistance(BaseModel):
    model_config = ConfigDict(extra="forbid", from_attributes=True)
    case_id: UUID
    task_id: Annotated[UUID | None, WithJsonSchema({'type': ['string', 'null'], 'format': 'uuid'})]
    step_id: Annotated[UUID | None, WithJsonSchema({'type': ['string', 'null'], 'format': 'uuid'})]
    message: Annotated[str, Field(min_length=1, max_length=500)]
    attachment_ids: Annotated[list[UUID], Field(max_length=5)]
    preferred_mode: Literal['text', 'annotation']
    id: UUID
    counselor_id: UUID
    state: Literal['queued', 'accepted', 'resolved', 'cancelled']
    version: Annotated[int, Field(ge=1, le=2147483647)]
    created_at: datetime


class AssistanceAction(BaseModel):
    model_config = ConfigDict(extra="forbid", from_attributes=True)
    action: Literal['accept', 'resolve', 'cancel']
    note: Annotated[Annotated[str, Field(max_length=500)] | None, BeforeValidator(reject_null), WithJsonSchema({'type': 'string', 'maxLength': 500})] = Field(default=None, json_schema_extra=omit_default)


class MessageCreate(BaseModel):
    model_config = ConfigDict(extra="forbid", from_attributes=True, json_schema_extra={'anyOf': [{'properties': {'body': {'minLength': 1, 'pattern': '\\S'}}}, {'properties': {'attachment_ids': {'minItems': 1}}}]})
    body: Annotated[str, Field(max_length=2000)]
    attachment_ids: Annotated[list[UUID], Field(max_length=5)]


class SupportMessage(BaseModel):
    model_config = ConfigDict(extra="forbid", from_attributes=True, json_schema_extra={'anyOf': [{'properties': {'body': {'minLength': 1, 'pattern': '\\S'}}}, {'properties': {'attachment_ids': {'minItems': 1}}}]})
    body: Annotated[str, Field(max_length=2000)]
    attachment_ids: Annotated[list[UUID], Field(max_length=5)]
    id: UUID
    request_id: UUID
    author_id: UUID
    created_at: datetime


class Notification(BaseModel):
    model_config = ConfigDict(extra="forbid", from_attributes=True)
    id: UUID
    seq: Annotated[str, Field(max_length=20, pattern='^(0|[1-9][0-9]*)$')]
    type: Annotated[str, Field(min_length=1, max_length=80)]
    resource_type: Literal['task', 'submission', 'assistance', 'annotation', 'file', 'case']
    resource_id: UUID
    created_at: datetime
    read_at: Annotated[datetime | None, WithJsonSchema({'type': ['string', 'null'], 'format': 'date-time'})]


class NotificationPage(BaseModel):
    model_config = ConfigDict(extra="forbid", from_attributes=True)
    items: Annotated[list[Notification], Field(max_length=100)]
    next_seq: Annotated[str, Field(max_length=20, pattern='^(0|[1-9][0-9]*)$')]
    has_more: bool


class TrainingRecord(BaseModel):
    model_config = ConfigDict(extra="forbid", from_attributes=True)
    task_id: UUID
    title: Annotated[str, Field(min_length=1, max_length=120)]
    status: Literal['not_started', 'in_progress', 'paused', 'submitted', 'changes_requested', 'completed', 'cancelled']
    attempts: Annotated[int, Field(ge=0, le=2147483647)]
    hint_requests: Annotated[int, Field(ge=0, le=2147483647)]
    assistance_requests: Annotated[int, Field(ge=0, le=2147483647)]
    observed_elapsed_ms: Annotated[Annotated[int | None, WithJsonSchema({'type': ['integer', 'null'], 'minimum': 0, 'maximum': 2147483647})], Field(ge=0, le=2147483647)]
    measurement_note: Annotated[str, Field(max_length=500)]


class CasePage(BaseModel):
    model_config = ConfigDict(extra="forbid", from_attributes=True)
    items: Annotated[list[Case], Field(max_length=100)]
    next_cursor: Annotated[Annotated[str | None, WithJsonSchema({'type': ['string', 'null'], 'maxLength': 512})], Field(max_length=512)]
    has_more: bool


class FilePage(BaseModel):
    model_config = ConfigDict(extra="forbid", from_attributes=True)
    items: Annotated[list[FileAsset], Field(max_length=100)]
    next_cursor: Annotated[Annotated[str | None, WithJsonSchema({'type': ['string', 'null'], 'maxLength': 512})], Field(max_length=512)]
    has_more: bool


class PlanPage(BaseModel):
    model_config = ConfigDict(extra="forbid", from_attributes=True)
    items: Annotated[list[SopPlan], Field(max_length=100)]
    next_cursor: Annotated[Annotated[str | None, WithJsonSchema({'type': ['string', 'null'], 'maxLength': 512})], Field(max_length=512)]
    has_more: bool


class TaskPage(BaseModel):
    model_config = ConfigDict(extra="forbid", from_attributes=True)
    items: Annotated[list[Task], Field(max_length=100)]
    next_cursor: Annotated[Annotated[str | None, WithJsonSchema({'type': ['string', 'null'], 'maxLength': 512})], Field(max_length=512)]
    has_more: bool


class SubmissionPage(BaseModel):
    model_config = ConfigDict(extra="forbid", from_attributes=True)
    items: Annotated[list[Submission], Field(max_length=100)]
    next_cursor: Annotated[Annotated[str | None, WithJsonSchema({'type': ['string', 'null'], 'maxLength': 512})], Field(max_length=512)]
    has_more: bool


class AnnotationPage(BaseModel):
    model_config = ConfigDict(extra="forbid", from_attributes=True)
    items: Annotated[list[Annotation], Field(max_length=100)]
    next_cursor: Annotated[Annotated[str | None, WithJsonSchema({'type': ['string', 'null'], 'maxLength': 512})], Field(max_length=512)]
    has_more: bool


class AssistancePage(BaseModel):
    model_config = ConfigDict(extra="forbid", from_attributes=True)
    items: Annotated[list[Assistance], Field(max_length=100)]
    next_cursor: Annotated[Annotated[str | None, WithJsonSchema({'type': ['string', 'null'], 'maxLength': 512})], Field(max_length=512)]
    has_more: bool


class MessagePage(BaseModel):
    model_config = ConfigDict(extra="forbid", from_attributes=True)
    items: Annotated[list[SupportMessage], Field(max_length=100)]
    next_cursor: Annotated[Annotated[str | None, WithJsonSchema({'type': ['string', 'null'], 'maxLength': 512})], Field(max_length=512)]
    has_more: bool


class RecordPage(BaseModel):
    model_config = ConfigDict(extra="forbid", from_attributes=True)
    items: Annotated[list[TrainingRecord], Field(max_length=100)]
    next_cursor: Annotated[Annotated[str | None, WithJsonSchema({'type': ['string', 'null'], 'maxLength': 512})], Field(max_length=512)]
    has_more: bool
