"""Generate routes and architectural views from the module model, ORM and state machine."""

import argparse
import json
import tomllib
from pathlib import Path

import yaml
from app.bootstrap import metadata
from app.modules.training.public import TRANSITIONS
from sqlalchemy import UniqueConstraint

ROOT = Path(__file__).resolve().parents[1]


def artifacts():
    model = tomllib.loads((ROOT / "architecture.toml").read_text())
    route_lines = [
        "// Generated by tools/generate_architecture.py; do not edit.",
        "import type { RouteObject } from 'react-router';",
        "export const featureRoutes: (RouteObject & { role?: 'learner' | 'counselor' })[] = [",
    ]
    for r in model["routes"]:
        role = f", role: '{r['role']}'" if "role" in r else ""
        route_lines.append(
            f"  {{ path: '{r['path']}'{role}, lazy: async () => ({{ Component: (await import('../features/{r['feature']}/public')).{r['export']} }}) }},"
        )
    route_lines += ["];", ""]
    text = [
        "# 工程架构",
        "",
        "## 运行边界",
        "",
        "```mermaid",
        "flowchart TB",
        '  users["学员 / 辅导员 · 浏览器"] -->|HTTPS| gateway["Caddy · SPA / API 入口"]',
        '  future["后续小程序 / App"] -.->|同一 API| gateway',
        '  subgraph private["私有服务网络"]',
        '    api["FastAPI · Python 模块化单体"]',
        '    worker["Python worker · 作业租约 / 重试"]',
        '    db[("PostgreSQL 17 · 业务 / 会话 / 通知 / 作业")]',
        '    storage[("私有文件空间 · Local / S3 适配")]',
        "  end",
        "  gateway -->|HTTP /api/v1| api",
        "  api -->|SQL / 事务| db",
        "  worker -->|SKIP LOCKED / 租约| db",
        "  api -->|受控文件 IO| storage",
        "```",
        "",
        "容器与存储适配边界；虚线为后续客户端。业务用例由 API 编排，worker 独立领取持久化作业。",
        "",
        "## 允许的模块依赖",
        "",
        "```mermaid",
        "flowchart LR",
    ]
    for name, item in model["backend"].items():
        text.append(f'  {name}["{name}"]')
        for dep in item["depends_on"]:
            text.append(f"  {name} -->|public| {dep}")
    text += [
        "```",
        "",
        "跨模块只导入 public；core 不依赖基础设施，基础设施不导入业务模块。",
        "",
        "## 核心数据关系",
        "",
        "```mermaid",
        "erDiagram",
    ]
    core = {
        "users",
        "cases",
        "case_grants",
        "sop_plans",
        "sop_revisions",
        "sop_steps",
        "training_tasks",
        "step_progress",
        "submissions",
        "feedback",
        "assistance_requests",
        "support_messages",
        "annotations",
    }
    edges = set()
    for table in metadata.sorted_tables:
        if table.name not in core:
            continue
        for fk in table.foreign_key_constraints:
            target = next(iter(fk.elements)).column.table.name
            if target in core:
                columns = {column.name for column in fk.columns}
                unique_sets = [{column.name for column in table.primary_key.columns}] + [
                    {column.name for column in constraint.columns}
                    for constraint in table.constraints
                    if isinstance(constraint, UniqueConstraint)
                ]
                parent_card = "o|" if any(column.nullable for column in fk.columns) else "||"
                child_card = "o|" if any(key and key <= columns for key in unique_sets) else "o{"
                edges.add((target, table.name, parent_card, child_card))
    for parent, child, parent_card, child_card in sorted(edges):
        text.append(f"  {parent.upper()} {parent_card}--{child_card} {child.upper()} : references")
    text += [
        "```",
        "",
        "图示主要外键关系；组合外键、唯一性、部分索引和不可变触发器见迁移。",
        "",
        "## 训练状态",
        "",
        "```mermaid",
        "stateDiagram-v2",
        "  [*] --> not_started",
    ]
    for (source, command), target in TRANSITIONS.items():
        text.append(f"  {source.value} --> {target.value}: {command}")
    text += [
        "  completed --> [*]",
        "  cancelled --> [*]",
        "```",
        "",
        "## 部署依赖",
        "",
        "```mermaid",
        "flowchart LR",
    ]
    compose = yaml.safe_load((ROOT / "compose.yaml").read_text())
    for name, service in compose["services"].items():
        text.append(f'  {name}["{name}"]')
        for dep, condition in service.get("depends_on", {}).items():
            text.append(f"  {name} -->|{condition['condition']}| {dep}")
    text += [
        "```",
        "",
        "## 接口归属",
        "",
        "| 模块 | 契约操作 | 已接入 HTTP |",
        "| --- | ---: | ---: |",
    ]
    contract = yaml.safe_load((ROOT / "contracts/openapi.yaml").read_text())
    implemented = json.loads((ROOT / "contracts/implemented.json").read_text())
    groups = {}
    for item in contract["paths"].values():
        for method, op in item.items():
            if method not in {"get", "post", "put", "delete", "patch"}:
                continue
            prefix = op["operationId"].split("_")[0]
            module = {
                "auth": "identity",
                "health": "platform",
                "files": "infrastructure",
                "notifications": "infrastructure",
            }.get(prefix, prefix)
            total, wired = groups.get(module, (0, 0))
            groups[module] = total + 1, wired + int(op["operationId"] in implemented)
    for module, (total, wired) in sorted(groups.items()):
        text.append(f"| {module} | {total} | {wired} |")
    text += ["", "接口契约覆盖业务范围；健康检查接入 HTTP，业务路由在对应模块后续实现时登记。", ""]
    return {
        "apps/web/src/app/routes.generated.ts": "\n".join(route_lines),
        "apps/web/architecture.generated.json": json.dumps(model["frontend"], indent=2) + "\n",
        "docs/architecture.md": "\n".join(text),
    }


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    for name, content in artifacts().items():
        path = ROOT / name
        if args.check:
            if not path.exists() or path.read_text() != content:
                raise SystemExit(f"generated artifact drift: {name}")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
    print("Architecture artifacts: PASS")


if __name__ == "__main__":
    main()
